### PR TITLE
Fixed EcoNewsController bugs.

### LINKED ISSUE #73: [Eco-News, GET /econews/contentAndSourceForEcoNews/{id}] The response code 403 (Forbidden) is not documented in the response codes list
**Environment:** 
Windows 11 Home
Chrome 114.0.5735.91 (Official buid) (64-bit)
GreenCityDocker-3 is built and running.

**Reproducible:** always.

**Pre-conditions:**
User is logged in as Authorized User.
An econews is created.

**Steps to reproduce**
1.  Select the “Eco-news" controller.
2.  Select the method GET /econews/contentAndSourceForEcoNews/{id} .
3.  Set the "id" of the created econews as the value of the "id" parameter.
4.  Compare the returned response code with the list of documented response codes.

**Actual result:** The 403 (Forbidden) response code is not documented in the response codes list.

**Expected result:** The 403 (Forbidden) response code is documented in the response codes list.

### LINKED ISSUE #76: [Eco-News, POST/econews] The response code 415 (Unsupported Media Type) is not documented in the response codes list
**Environment:**
Windows 11 Home
Chrome 114.0.5735.91 (Official buid) (64-bit)
GreenCityDocker-3 is built and running.

**Reproducible:** always.

**Pre-conditions:**
User is logged in.

**Steps to reproduce:**

1. Select the “Eco-news" controller.
2. Select the method POST/econews .
3. Do not add the formData (addEcoNewsDtoRequest ).
4. Send the request.
5. Compare the returned response code with the list of documented response codes.

**Actual result:**
The 415 (Unsupported Media Type) response code is not documented in the response codes list

**Expected result:**
The 415 (Unsupported Media Type) response code is documented in the response codes list

### LINKED ISSUE #77: [Eco-News, DELETE /econews/{econewsId}] The 403 (Forbidden) response code is not documented in the response codes list.
**Environment:** 
Windows 11 Home
Chrome 114.0.5735.91 (Official buid) (64-bit)
GreenCityDocker-3 is built and running.

**Reproducible:** always.

**Pre-conditions:**
User is logged in as User
There is an Econews created by another User (eg.User2)
**Steps to reproduce**
1.  Select the “Eco-news" controller.
2.  Select the method DELETE /econews/{econewsId} .
3.  Set the "Id" of the econews created by another User (eg User2) as the value of the "econewsId".
4.  Send the request.
5.  Compare the returned response code with the list of documented response codes.

**Actual result:**
Response code 403 (Forbidden) is not documented in the response codes list.

**Expected result:**
Response code 403 (Forbidden) is documented in the response codes list.

### LINKED ISSUE #78: [Eco-News, DELETE /econews/{econewsId}] The 400 (Bad request) response code is not documented in the response codes list.
**Environment:** 
Windows 11 Home
Chrome 114.0.5735.91 (Official buid) (64-bit)
GreenCityDocker-3 is built and running.

**Reproducible:** always.

**Pre-conditions:**
User is logged in as User

**Steps to reproduce**
1.  Select the “Eco-news" controller.
2.  Select the method DELETE /econews/{econewsId} .
3.  Set the letters (eg. ABC) as the value of the "econewsId".
4.  Send the request.
5.  Compare the returned response code with the list of documented response codes.

**Actual result:**
Response code 400 (Bad request) is not documented in the response codes list.

**Expected result:**
Response code 400 (Bad request) is documented in the response codes list.

### LINKED ISSUE #79: [Eco-News, GET /econews/byUserPage] The 401 (Unauthorized) response code is not documented in the list of response
**Environment:** 
Windows 11 Home
Chrome 114.0.5735.91 (Official buid) (64-bit)
GreenCityDocker-3 is built and running.

**Reproducible:** always.

**Pre-conditions:**
User is not authorized 

**Steps to reproduce**
1.  Select the “Eco-news" controller
2.  Select the method GET/econews/byUserPage.
3.  Send the request
4.  Compare the returned response code with the list of documented response codes.

**Actual result:**
Response code 401 (Unauthorized) is not documented in the response codes list.

**Expected result:**
Response code 401 (Unauthorized) is documented in the response codes list.

### PR DESCRIPTION
**Pull request by Linney34**
## Summary by CodeRabbit

* **Documentation**
  * Enhanced API documentation by adding new response codes including 415 Unsupported Media Type, 403 Forbidden, 400 Bad Request, and 401 Unauthorized for multiple endpoints.

### CODE REVIEW

File: core/src/main/java/greencity/controller/EcoNewsController.java [hunk 1]
```diff
@@ -384,6 +387,7 @@ public ResponseEntity<Boolean> checkNewsIsLikedByUser(@RequestParam("econewsId")
         @ApiResponse(responseCode = "200", description = HttpStatuses.OK),
         @ApiResponse(responseCode = "400", description = HttpStatuses.BAD_REQUEST),
         @ApiResponse(responseCode = "401", description = HttpStatuses.FORBIDDEN),
+        @ApiResponse(responseCode = "403", description = HttpStatuses.FORBIDDEN),
```
Comment (MykytaSirobaba) [inline core/src/main/java/greencity/controller/EcoNewsController.java:399]: Hi! You added @ApiResponse(responseCode = "403", description = HttpStatuses.FORBIDDEN), but you didn't update the existing @ApiResponse(responseCode = "401", description = HttpStatuses.FORBIDDEN) — it should be 401 **Unauthorized** instead of **FORBIDDEN**.

**Review by MykytaSirobaba — CHANGES_REQUESTED** [review]

File: core/src/main/java/greencity/controller/EcoNewsController.java (hunk 1 above)
Comment (Linney34) [reply core/src/main/java/greencity/controller/EcoNewsController.java:399]: Hi! That's because I fixed this issue in previous branch 😁

**Review by MykytaSirobaba — APPROVED** [review]

File: core/src/main/java/greencity/controller/EcoNewsController.java [hunk 2]
```diff
@@ -384,6 +389,7 @@ public ResponseEntity<Boolean> checkNewsIsLikedByUser(@RequestParam("econewsId")
         @ApiResponse(responseCode = "200", description = HttpStatuses.OK),
         @ApiResponse(responseCode = "400", description = HttpStatuses.BAD_REQUEST),
         @ApiResponse(responseCode = "401", description = HttpStatuses.FORBIDDEN),
```
Comment (Kostya-Pav) [inline core/src/main/java/greencity/controller/EcoNewsController.java]: 401 - UNAUTHORIZED

**Review by Kostya-Pav — APPROVED** [review]
