### PR TITLE
59 bug eco news posteconews the addeconewsdtorequest form data model has to be updated

### LINKED ISSUE #59: [Eco-News, POST/econews] The "addEcoNewsDtoRequest" form-data model has to be updated
**Environment:** 
Windows 11 Home
Chrome 114.0.5735.91 (Official buid) (64-bit)
GreenCityDocker-3 is built and running.

**Reproducible:** always.

**Pre-conditions:**
User is not logged in

**Steps to reproduce**
1. Select the “Eco-news" controller.
2. Select the method POST/econews.
3. Pay attention to the "addEcoNewsDtoRequest" form-data model.

**Actual result:** 
The "addEcoNewsDtoRequest" form-data model:

{
  "image": "string",
  "source": "https://example.org/",
  "shortInfo": "string",
  "tags": [
    "string"
  ],
  "titleTranslation":
     {"content": "string",
     "languageCode": "string"},
  "textTranslation":
     {"content": "string",
     "languageCode": "string"}
}

**Expected result:** 
The "addEcoNewsDtoRequest" form data model:

{"tags":["string"],"text":"string","title":"string","source":"string"}

### PR DESCRIPTION
**Pull request by Kostya-Pav**
## Summary by CodeRabbit

* **New Features**
  * Added a simplified example for adding eco news in the API documentation.

* **Improvements**
  * Updated the eco news request example in API documentation to be more concise.
  * The add eco news API now includes an Authorization header for improved security.

* **Tests**
  * Enhanced tests to include authorization headers when adding eco news.

* **Style**
  * Reformatted comments in the GitHub Actions workflow file for improved readability.

### CODE REVIEW

**Review by AndriiSynytsia — APPROVED** [review]

**Review by MykytaSirobaba — APPROVED** [review]

File: core/src/main/java/greencity/constant/SwaggerExampleModel.java [hunk 1]
```diff
@@ -14,6 +14,13 @@ public final class SwaggerExampleModel {
         + "\t</ul>\n"
         + "\t<pre>\n";
 
+    private static final String EXAMPLE_FOR_ADD_ECO_NEWS =
+            "  \"title\": \"string\",\n"
+            + "  \"text\": \"string\",\n"
+            + "  \"tags\": [\"valid tag\"],\n"
+            + "  \"source\": \"https://example.org\",\n"
+            + "  \"shortInfo\": \"string\"\n";
+
```
Comment (natri0) [inline core/src/main/java/greencity/constant/SwaggerExampleModel.java:23]: this is only used in one place currently (the "add econews" example), so maybe just include it as-is? no need for a separate constant.

also, the `EXAMPLE` variable is now only used in one place as well (the "update econews") example, so would be good to either keep both like this or remove both.

File: core/src/main/java/greencity/constant/SwaggerExampleModel.java [hunk 2]
```diff
@@ -45,7 +52,7 @@ public final class SwaggerExampleModel {
             + IMAGE_DESCRIPTION
             + BEFORE_EXAMPLE
             + "{\n"
-            + EXAMPLE
+            + EXAMPLE_FOR_ADD_ECO_NEWS
```
Comment (natri0) [inline core/src/main/java/greencity/constant/SwaggerExampleModel.java:55]: re: above comment

```suggestion
            + "  \"title\": \"string\",\n"
            + "  \"text\": \"string\",\n"
            + "  \"tags\": [\"valid tag\"],\n"
            + "  \"source\": \"https://example.org\",\n"
            + "  \"shortInfo\": \"string\"\n"
```

**Review by natri0 — APPROVED** [review]
minor comments
